# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays: 
1. A 1-D array called zeros having 10 elements and all the elements are set to zero. 
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. 
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13 
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [29]:
# Write your answer here
import numpy as np
q1 = zeros = np.zeros(10)
zeros
q2 = vowels = np.array(['a','e','i','o','u'])
vowels
q3 = ones = np.ones(10, dtype=int).reshape(2,5)
ones
q4 = myarray = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])
myarray
q5 = myarray2 = np.arange(4, 4+15*4, 4).reshape(3,5)
myarray2

array([[ 4,  8, 12, 16, 20],
       [24, 28, 32, 36, 40],
       [44, 48, 52, 56, 60]])

Using the arrays created in Question above, write NumPy commands for the following: 
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 
2. Reshape the array ones to have all the 10 elements in a single row. 
3. Display the 2nd and 3rd element of the array vowels. 
4. Display all elements in the 2nd and 3rd row of the array myarray1. 
5. Display the elements in the 1st and 2nd column of the array myarray1. 
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
7. Reverse the array of vowels.

In [65]:
#Write your answer here            dtype.type --> if you dont want to show 'dtype' in result
q1 = myarray2.shape, myarray2.size, myarray2.ndim, myarray2.dtype.type, myarray2.itemsize
q2 = ones.reshape(1,10)
q3 = vowels[1:3]
q4 = myarray[1:3 , : ]
print(myarray)
q5 = myarray[ :  , 0:2]
q6 = myarray[ 1:3 , 0:1]
q7 = vowels[::-1]

[[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]


array(['u', 'o', 'i', 'e', 'a'], dtype='<U1')

Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3. 
2. Add the arrays myarray1 and myarray2. 
3. Subtract myarray1 from myarray2 and store the result in a new array. 
4. Multiply myarray1 and myarray2 elementwise. 
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
6. Divide myarray1 by myarray2. 
7. Find the cube of all elements of myarray1 and divide the resulting array by 2. 
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [185]:
# Write your answer here
q1 = ones/3
# myarray.shape, myarray2.shape
q2 = myarray + myarray2[ : , 0:3]
q3 = arr5 = myarray - myarray2[:, :3]
arr5
q4 = myarray * myarray2[ : , 0:3]
q5 = result = myarray2.T.dot(myarray)
result
q6 = myarray / myarray2[:, :3]
q7 = (myarray**3)/2
q8 = np.round( (np.sqrt(myarray2))/2, 2 )

array([[ 0.675     ,  0.        , -0.16666667],
       [ 0.14166667,  0.37857143,  0.        ],
       [-0.43181818,  2.08125   ,  0.25      ]])

Using the arrays created above, write NumPy commands for the following: 
1. Find the transpose of ones and myarray2. 
2. Sort the array vowels in reverse. 
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [95]:
# Write your answer here
q1 = np.transpose(myarray2) #myarray2.T
q2 = vowels[::-1]
q3 = np.sort(myarray,1)  # 1 for sorting by row, and 0 for sorting by column

array([[ -2. ,   0. ,   2.7],
       [  0. ,   3.4,  10.6],
       [-19. ,  13. ,  99.9]])

Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result. 

In [103]:
# Write your answer here
myarray4 = np.arange(-1, -1+42*0.25 , 0.25).reshape(14,3)
myarray4


array([[-1.  , -0.75, -0.5 ],
       [-0.25,  0.  ,  0.25],
       [ 0.5 ,  0.75,  1.  ],
       [ 1.25,  1.5 ,  1.75],
       [ 2.  ,  2.25,  2.5 ],
       [ 2.75,  3.  ,  3.25],
       [ 3.5 ,  3.75,  4.  ],
       [ 4.25,  4.5 ,  4.75],
       [ 5.  ,  5.25,  5.5 ],
       [ 5.75,  6.  ,  6.25],
       [ 6.5 ,  6.75,  7.  ],
       [ 7.25,  7.5 ,  7.75],
       [ 8.  ,  8.25,  8.5 ],
       [ 8.75,  9.  ,  9.25]])

Using the myarray4 created in the above questions, write commands for the following: 
1. Find the sum of all elements. 
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise. 
4. Find the max of all elements. 
5. Find the min of all elements in each row. 
6. Find the mean of all elements in each row. 
7. Find the standard deviation column wise.

In [125]:
# Write your ansewr here
q1 = np.sum(myarray4)
q2 = np.sum(myarray4,axis = 0) # 0 for rows
q3 = np.sum(myarray4,axis = 1) #1 for column
q4 = np.max(myarray4)
q5 = np.min(myarray4,axis = 0)
q6 = np.mean(myarray4, axis =0)
q7 = np.std(myarray4,axis = 1)

array([3.875, 4.125, 4.375])

#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [54]:
# Write your answer here

import os
os.getcwd()
import pandas as pd
import numpy as np
capital = pd.read_csv('country-capital-lat-long-population.csv')
capital

riyadh = capital[capital['Country'] == 'Saudi Arabia'][['Latitude', 'Longitude']].values[0] # riyadh coordinates
distances = np.sqrt(np.sum((capital[['Latitude', 'Longitude']].astype(float) - riyadh) ** 2, axis=1)) # Euclidean distances
closest_index = np.argsort(distances)[1]  # 1 cuz if its 0 then it would be riyadh 
closest_capital = capital.iloc[closest_index] # location of the closest capital

print(f"Capital: {closest_capital['Capital City']}", f", {closest_capital['Country']}")
print(f"Coordinates: {closest_capital['Latitude']}, {closest_capital['Longitude']}")


Capital: Al-Manamah (Manama) , Bahrain
Coordinates: 26.2154, 50.5832


#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [56]:
# 1
import os
os.getcwd()
import pandas as pd
import numpy as np
capital = pd.read_csv('country-capital-lat-long-population.csv')
capital

washington_dc = capital[capital['Capital City'] == 'Washington'][['Latitude', 'Longitude']] # washington coordinates
distances = np.sqrt(np.sum((capital[['Latitude', 'Longitude']].astype(float) - washington_dc) ** 2, axis=1)) # Euclidean distances
countries10 = capital['Country'][np.argsort(distances)[1:11]] # top 10 countries closest to washington
countries10



148               New Caledonia
149                 New Zealand
150                   Nicaragua
151                       Niger
152                     Nigeria
153                        Niue
154    Northern Mariana Islands
155                      Norway
156                        Oman
157                    Pakistan
Name: Country, dtype: object

In [58]:
# 2
import numpy as np
capital = pd.read_csv('country-capital-lat-long-population.csv')

washington_dc = capital[capital['Capital City'] == 'Washington'][['Latitude', 'Longitude']]
distances = np.sqrt(np.sum((capital[['Latitude', 'Longitude']].astype(float) - washington_dc) ** 2, axis=1)) 
indices = np.argsort(distances)[1:11] 
coordinates_10 = capital.iloc[indices][['Latitude', 'Longitude']].to_numpy() # converting to NumPy array 

coordinates_10

array([[ -22.2763,  166.4572],
       [ -41.2866,  174.7756],
       [  12.1328,  -86.2504],
       [  13.5137,    2.1098],
       [   9.0574,    7.4898],
       [ -19.0585, -169.9213],
       [  15.2123,  145.7545],
       [  59.9127,   10.7461],
       [  23.6139,   58.5922],
       [  33.7035,   73.0594]])